export const NestingThemesCode = 
'{/* Default theming */}\n'
+ '<Header as="h4" content="Default theming" />\n'
+ '<Button content="Button" />'
+ '<Button content="Button" />\n'
+ '<Button icon={<AddIcon />} iconOnly primary />\n'
+ '<Button icon={<EmailIcon />} content="Send email" secondary />\n'
+ '<EmojiIcon size="larger" />\n'
+ '<Label content="Label with icon" icon={<CloseIcon />} />\n'
+ '\n'
+ '{/* First nested theming */}\n'
+ '<Provider\n'
+ '  theme={{\n'
+ '    componentVariables: {\n'
+ '      Button: {\n'
+ '        primaryBackgroundColor: "darkred",\n'
+ '      },\n'
+ '    },\n'
+ '  }}\n'
+ '>\n'
+ '  <div>\n'
+ '    <Header as="h4" content="First nested theming" />\n'
+ '    \n'
+ '    <Button content="Button" />\n'
+ '    <Button icon={<AddIcon />} iconOnly primary />\n'
+ '    <Button icon={<EmailIcon />} content="Send email" secondary />\n'
+ '    <EmojiIcon size="larger" />\n'
+ '    <Label content="Label with icon" icon={<CloseIcon />} />\n'
+ '    \n'
+ '    {/* Second nested theming */}\n'
+ '    <Provider\n'
+ '      theme={{\n'
+ '        componentStyles: {\n'
+ '          Button: {\n'
+ '            root: { color: "goldenrod" },\n'
+ '          },\n'
+ '        },\n'
+ '      }}\n'
+ '    >\n'
+ '      <div>\n'
+ '        <Header as="h4" content="Second nested theming" />\n'
+ '        \n'
+ '        <Button content="Button" />\n'
+ '        <Button icon={<AddIcon />} iconOnly primary />\n'
+ '        <Button icon={<EmailIcon />} content="Send email" secondary />\n'
+ '        <EmojiIcon size="larger" />\n'
+ '        <Label content="Label with icon" icon={<CloseIcon />} />\n'
+ '      </div>\n'
+ '    </Provider>\n'
+ '  </div>\n'
+ '</Provider>\n';

export const FlexGapCode = 
    '<Flex gap="gap.small">\n'
  + '  <Segment color="brand" content="Home" inverted />\n'
  + '  <Segment color="green" content="Search" inverted />\n'
  + '  <FlexItem push>\n'
  + '    <Segment color="red" content="Logout" inverted />\n'
  + '  </FlexItem>\n'
  + '</Flex>\n'
  + '<Flex column>\n'
  + '  <Segment color="brand" content="Header" inverted />\n'
  + '  <Segment content="Content" />\n'
  + '  <Segment color="green" content="Footer" inverted />\n'
  + '</Flex>\n'

export const FlexColumnCode = 
    '<Flex column>\n'
  + '  <Segment color="brand" content="Header" inverted />\n'
  + '  <Segment content="Content" />\n'
  + '  <Segment color="green" content="Footer" inverted />\n'
  + '</Flex>\n'

export const GridFourCode = 
    '<Grid columns="repeat(4, 1fr)" rows="50px 150px 50px">\n'
  + '  <Segment\n'
  + '    color="brand"\n'
  + '    content="Header"\n'
  + '    inverted\n'
  + '    styles={{\n'
  + '      gridColumn: "span 4",\n'
  + '    }}\n'
  + '  />\n'
  + '  <Segment\n'
  + '    color="green"\n'
  + '    content="Menu"\n'
  + '    inverted\n'
  + '    styles={{\n'
  + '      gridColumn: "span 1",\n'
  + '    }}\n'
  + '  />\n'
  + '  <Segment\n'
  + '    content="Content"\n'
  + '    styles={{\n'
  + '      gridColumn: "span 3",\n'
  + '    }}\n'
  + '  />\n'
  + '  <Segment\n'
  + '    color="brand"\n'
  + '    content="Footer"\n'
  + '    inverted\n'
  + '    styles={{\n'
  + '      gridColumn: "span 4",\n'
  + '    }}\n'
  + '  />\n'
  + '</Grid>\n'
  
export const GridTwoCode = 
    '<Grid columns="repeat(2, 1fr)">\n'
  + '  <Segment\n'
  + '    color="brand"\n'
  + '    content="Header"\n'
  + '    inverted\n'
  + '    styles={{\n'
  + '      gridColumn: "1/3",\n'
  + '      gridRow: 1,\n'
  + '    }}\n'
  + '  />\n'
  + '  <Segment\n'
  + '    color="red"\n'
  + '    content="Menu"\n'
  + '    inverted\n'
  + '    styles={{\n'
  + '      gridColumn: "3",\n'
  + '      gridRow: "1/3",\n'
  + '    }}\n'
  + '  />\n'
  + '  <Segment\n'
  + '    color="green"\n'
  + '    content="Notes"\n'
  + '    inverted\n'
  + '    styles={{\n'
  + '      gridColumn: "1",\n'
  + '      gridRow: "2",\n'
  + '    }}\n'
  + '  />\n'
  + '  <Segment\n'
  + '    color="grey"\n'
  + '    content="News"\n'
  + '    inverted\n'
  + '    styles={{\n'
  + '      gridColumn: "2",\n'
  + '      gridRow: "2",\n'
  + '    }}\n'
  + '  />\n'
  + '</Grid>\n'